//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value contains non existing directory path: &quot;{0}&quot;. ähnelt.
        /// </summary>
        internal static string ArgumentDirectoryNotExistsTemplate {
            get {
                return ResourceManager.GetString("ArgumentDirectoryNotExistsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be &quot;{0}&quot;. Is &quot;{1}&quot;. ähnelt.
        /// </summary>
        internal static string ArgumentEqualCompareCurrentTemplate {
            get {
                return ResourceManager.GetString("ArgumentEqualCompareCurrentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value contains none-existing file path: &quot;{0}&quot;. ähnelt.
        /// </summary>
        internal static string ArgumentFileNotExistsTemplate {
            get {
                return ResourceManager.GetString("ArgumentFileNotExistsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List must contain at least one element. ähnelt.
        /// </summary>
        internal static string ArgumentListNotEmptyMaxLength {
            get {
                return ResourceManager.GetString("ArgumentListNotEmptyMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum filesize exceeded. Size: {0} (max.: {1}). ähnelt.
        /// </summary>
        internal static string ArgumentMaxFileSizeExceededSizeTemplate {
            get {
                return ResourceManager.GetString("ArgumentMaxFileSizeExceededSizeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text exceeds maximum length of {0} characters. ähnelt.
        /// </summary>
        internal static string ArgumentMaxLengthTemplate {
            get {
                return ResourceManager.GetString("ArgumentMaxLengthTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be false. ähnelt.
        /// </summary>
        internal static string ArgumentMustBeFalse {
            get {
                return ResourceManager.GetString("ArgumentMustBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be negative. ähnelt.
        /// </summary>
        internal static string ArgumentMustBeNegative {
            get {
                return ResourceManager.GetString("ArgumentMustBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be null. ähnelt.
        /// </summary>
        internal static string ArgumentMustBeNull {
            get {
                return ResourceManager.GetString("ArgumentMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be positive. ähnelt.
        /// </summary>
        internal static string ArgumentMustBePositive {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be true. ähnelt.
        /// </summary>
        internal static string ArgumentMustBeTrue {
            get {
                return ResourceManager.GetString("ArgumentMustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Type {0} needs to implement interface {1}&quot;. ähnelt.
        /// </summary>
        internal static string ArgumentMustImplementTemplate {
            get {
                return ResourceManager.GetString("ArgumentMustImplementTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must not be of type&apos;s default value. ähnelt.
        /// </summary>
        internal static string ArgumentMustNotBeDefault {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must not be null. ähnelt.
        /// </summary>
        internal static string ArgumentMustNotBeNull {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must not be equal to &quot;{0}&quot;. ähnelt.
        /// </summary>
        internal static string ArgumentNotEqualCurrentTemplate {
            get {
                return ResourceManager.GetString("ArgumentNotEqualCurrentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must not be greater than {0}. (Is {1}). ähnelt.
        /// </summary>
        internal static string ArgumentNotGreaterThanMaxCurrentTemplate {
            get {
                return ResourceManager.GetString("ArgumentNotGreaterThanMaxCurrentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must not be greater than or equal to &quot;{0}&quot;. Is &quot;{1}&quot;. ähnelt.
        /// </summary>
        internal static string ArgumentNotGreaterThanOrEqualMaxCurrentTemplate {
            get {
                return ResourceManager.GetString("ArgumentNotGreaterThanOrEqualMaxCurrentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must not be smaller than &quot;{0}&quot;. Is &quot;{1}&quot;. ähnelt.
        /// </summary>
        internal static string ArgumentNotLessThanMaxCurrentTemplate {
            get {
                return ResourceManager.GetString("ArgumentNotLessThanMaxCurrentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must not be smaller than or equal to &quot;{0}&quot;. Is &quot;{1}&quot;. ähnelt.
        /// </summary>
        internal static string ArgumentNotLessThanOrEqualMaxCurrentTemplate {
            get {
                return ResourceManager.GetString("ArgumentNotLessThanOrEqualMaxCurrentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String cannot be empty. ähnelt.
        /// </summary>
        internal static string ArgumentValueNotEmpty {
            get {
                return ResourceManager.GetString("ArgumentValueNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Critical ähnelt.
        /// </summary>
        internal static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug ähnelt.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dictionary ähnelt.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List ähnelt.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trace ähnelt.
        /// </summary>
        internal static string Trace {
            get {
                return ResourceManager.GetString("Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
